name: Android UI Tests with Espresso

on:
  push:
    branches:
      - pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run UI test via Gradle Virtual Devices
        run: ./gradlew -Pandroid.experimental.androidTest.useUnifiedTestPlatform=true phoneAndTabletGroupDebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: app/build/reports/androidTests/managedDevice/allDevices

